### ISSUE TITLE
Use the user.challenges[x].timestamp instead of querying the events.

### ISSUE THREAD

**Issue by carletex** [moonshotcollective/scaffold-directory#139]
We can tackle this whenever the current review log is cleaned up.

....We can also start thinking about firebase subcollections, but not a priority.

**Comment by dgrcode** [comment]
I don't have a PR open yet. I'll make the changes tomorrow, on top of #147 when merged. In the meantime, these are the tasks:
- [x] Manually update the pending submitted challenges without `submittedTimestamp` field in firestore
- [ ] Show side by side the `user.challenges[x].submittedTimestamp` and the currently computed timestamp to find any discrepancy. Fix any issues found here.
- [ ] Remove legacy (current) code and leave only the code using `user.challenges[x].submittedTimestamp`

One thing we could easily add: sort the challenges by date. Not sure if oldest or newest first, but once we already have timestamps without further fetches, we can easily sort them by date.

Allowing to sort asc/desc by clicking in the header might be a bit more complex and it's probably worth a separate issue, but default-sorting them should be really simple and make the experience better.

WDYT @carletex?

**Comment by carletex** [comment]
> One thing we could easily add: sort the challenges by date. Not sure if oldest or newest first, but once we already have timestamps without further fetches, we can easily sort them by date.

Yep, that would be cool. I'd say let's do ASC (oldest first): I think it makes more sense to attend older submitted challenge.

> Allowing to sort asc/desc by clicking in the header might be a bit more complex and it's probably worth a separate issue, but default-sorting them should be really simple and make the experience better.

I was discussing earlier today with some admins/reviewers and they have some UX suggestions in the review page. Opening a new issue for it #148
