### ISSUE TITLE
README.md git clone

### ISSUE THREAD

**Issue by wkarshat** [moonshotcollective/scaffold-directory#154]
Does this host specification actually work?
`git@github.com:`

**Comment by carletex** [comment]
It does (if you have your SSH keys set up).

![image](https://user-images.githubusercontent.com/2486142/147340953-5102d3da-9b49-4c6c-93a0-8d2a2f820e2b.png)

If you don't authenticate with SSH keys, you will need to use HTTPS:

![image](https://user-images.githubusercontent.com/2486142/147341023-37e858f8-9168-4cba-9294-844e1a297d75.png)

`git clone https://github.com/moonshotcollective/scaffold-directory.git`
