### ISSUE TITLE
Rename/Refactor the ProfileView into BuilderHomeView (or something else)?

### ISSUE THREAD

**Issue by sogasg** [moonshotcollective/scaffold-directory#22]
I think the name `profile` for the page showing a user's learning paths might be confusing, and also easily confused with the BuilderProfile page.

I propose renaming the ProfileView into BuilderHomeView.

What do you think @carletex and @dgrcode?

**Comment by dgrcode** [comment]
Yes, I agree it's confusing. Let's rename it.
