### ISSUE TITLE
Performance: App re-renders with every blockchain block

### ISSUE THREAD

**Issue by dgrcode** [moonshotcollective/scaffold-directory#26]
I don't know how easy/hard would be to fix this, but given that we're mostly doing web2 stuff, there's no need to be refreshing the whole app with every blockchain block.

I imagine this is just going to be removing some hook inside App.js. If it's going to be harder than that, we can just leave it as is ¯\\\_(ツ)_/¯

(cc @carletex @sogasg)

**Comment by carletex** [comment]
Yep, right now we don't need any on-chain data so we should be safe removing it.

**Comment by codenamejason** [comment]
I would also check any useEffects you may have and make sure the object that it is monitoring is not being updated every block also ie: readContracts & writeContracts.
