### ISSUE TITLE
Remove tokens (JWTs)

### ISSUE THREAD

**Issue by dgrcode** [moonshotcollective/scaffold-directory#29]
EDIT

This issue has been split into two tasks:
 - This one is for updating the expiry date to a month or refreshing the token
 - #39 is for the endpoint splitting (and other stuff unrelated with the original intention of this issue)

Original issue for reference below:
  
---
The firebase library, which we're using to generate the token, adds a bunch of stuff to the token metadata. One of them is the expiry date.

I think we'll need a new endpoint to do pretty much the same as `POST /sign`, because now users will be able to access everything using the JWT instead of using the address stored in the local storage. So the flow would be:
 - Does user have a valid JWT token? Go to `/home`, and from there fetch the new route `GET /builder-data` (for example) using the JWT to authenticate, and there generate a new JWT to update the expiry date.
 - Is JWT expired or inexistent? Go to `/` to sign a new message and re-authenticate using `POST /sign`

Both endpoints will have plenty of shared logic, so I suggest extracting that logic into a separate function.

The refreshing logic could be implemented in the middleware, adding a `req.refreshToken` in the express request, that is then sent to the client. The client can use the refresh token to replace the token stored locally.

(cc @carletex @sogasg)

**Comment by carletex** [comment]
I discussed this with @dgrcode on a quick call.

We'll do a separate unauthenticated endpoint (/sign or /login) to allow the user getting a valid JWT. Then we can get all the data with freshly create JWT.

**Comment by dgrcode** [comment]
After the changes introduced in #44 and #46, there's no longer need for JWTs. This issue is going to be used to remove jwt usage instead of refreshing them.

**Comment by dgrcode** [comment]
Removing a useful view used for manually testing JWTs. For reference, the last working version of `JwtTest.jsx`: https://github.com/moonshotcollective/scaffold-directory/blob/3cdd9965b8c6fa33168eacffbe3ff275fa827a0b/packages/react-app/src/views/JwtTest.jsx

**Comment by dgrcode** [comment]
Fixed by #56
