### ISSUE TITLE
Admin logic

### ISSUE THREAD

**Issue by carletex** [moonshotcollective/scaffold-directory#34]
- Store `admin` flag on JWT & firebase.
- Use it to allow access to the Challenge review page (+ backend middleware to protect the challenge-review-submission)
- Show `admin` badge in the UI.

Dependent on #31 #32

**Comment by carletex** [comment]
@dgrcode @sogasg Thinking about the nodejs middleware to protect admin routes (like challenge-review data).

I see 3 options:
1. Expanding the middleware [jwt middleware](https://github.com/moonshotcollective/scaffold-directory/blob/3e70e744685527a0fe5df6b87a94783bdbd749f1/packages/backend/middlewares/auth.js): We could wrap the middleware in a function (that returns a function) that takes a param (like admin =  TRUE). In the route we'd call it like `jwtAuth(true)`
2. Create a new (full) middleware: We might use the same logic as in jwtAuth + add the admin logic. In the route: `jwtAdminAuth`
3. Creata a new (partial) middleware: Only with the admin logic. In the route we would have to use both: `jwtAuth`, `isAdmin`

What do you think?

**Comment by dgrcode** [comment]
I think we can go with 2. However, we won't need to extract the jwtAuth logic, we can just call it. Something like this:
```js
const adminAuth = (req, res, next) => {
  jwtAuth(req, res, () => {}) // don't call the next function when this middleware finishes

  // jwtAuth reads the token and adds values to req.
  // So far we only add the address, but we can add `.isAdmin`
  if (!req.isAdmin) {
    res.sendStatus(401)
    return
  } 

  next() // go to the endpoint handler, or the next middleware if there's one
}
```

That code might not be working code (we might need to call the middleware with`await`, and I'm not 100% sure about the `() => {}` as 3rd argument on the middleware call), but just to show the general idea.
