### ISSUE TITLE
Detail challenge page

### ISSUE THREAD

**Issue by carletex** [moonshotcollective/scaffold-directory#4]
Route `/challenge/{id}`

**Comment by dgrcode** [comment]
@carletex @sogasg I'll take this one. My plan is to:
 - Make the challenges in the challenge list link to `/challenge/{id}`
 - Create a basic page where we show the challenge details, as well as the challenge status for the logged in user
 - "Ant'ify" the parts that I touch of the challenge list and the new code in the details page

Feel free to chime in if you want to see more things done as part of this ticket.
