### ISSUE TITLE
changing `scaffold-directory-is-admin` gives admin permissions on the client

### ISSUE THREAD

**Issue by dgrcode** [moonshotcollective/scaffold-directory#50]
The back end is still protected, but I wanted to put this here in case you can think of some possible attack people might attempt here.

We should probably consider not storing `isAdmin` on the localStorage, and always check the token. We could have a `useToken` hook to get content from there.

Anything on the client can always be "hacked", but this aims to make it harder than just look at the local storage, looking for the word "admin" and turning it to true.

**Comment by carletex** [comment]
> We should probably consider not storing isAdmin on the localStorage, and always check the token. We could have a useToken hook to get content from there.

Yep, I think this make the more sense.

**Comment by dgrcode** [comment]
This no longer applies after removing the JWT in #29
