### ISSUE TITLE
When signing in, the "Home" tab looks active, however the URL and the content is from the "My Profile" view

### ISSUE THREAD

**Issue by sogasg** [moonshotcollective/scaffold-directory#61]
<img width="1027" alt="Screenshot 2021-09-29 at 13 30 34" src="https://user-images.githubusercontent.com/2156509/135260318-b67a389b-6713-48fe-a1a6-9c8ec41da509.png">

**Comment by carletex** [comment]
This is fixed on #59 

this commit https://github.com/moonshotcollective/scaffold-directory/pull/59/commits/a4d2eed4634fda89f85d80d60e15c5ed1bb4ef52

**Comment by sogasg** [comment]
Sorry about that. I was still on the old version of branch #47 🤦
