### ISSUE TITLE
Build submission form for Builders

### ISSUE THREAD

**Issue by carletex** [moonshotcollective/scaffold-directory#98]
Needs #97 

Builders can submit new builds to the list. From Austin:

> I think letting people submit/propose repo urls to add to the “builds” list. We can coach them in the submission form to make a good readme and then they can turn the repo in as a build. I think that probably leads to a new “builder” role on the site that you get after completing a challenge or two. This builder role unlocks all the cool views like builds, activity feed, etc. (I think activity feed is fun next priority too. Getting to see people submit builds and complete challenges sounds like a lot of fun)

**Comment by dgrcode** [comment]
- [ ] Add a prop in the build `isDraft: true` to know when a build is not approved yet.
 - [ ] Add events when different things happen
 - [ ] Button for the builder to submit from `/builds`
 - [ ] Add a section in the review page to review submitted builds
